---
title: "Generative Jamaica Road Art"
author: Taelor Malcolm
output: html_document
---

```{r setup}
#load libraries
library(osmdata)
library(sf)
library(ggplot2)
library(ggforce)
library(dplyr)
```

```{r road data gathering}
#Jamaica boundary box
jamaica_bb <- getbb("Jamaica") %>%
  replace(is.na(.), 0)

# Get water features - RIVERS
water_features <- opq(jamaica_bb) %>%
  add_osm_feature(key = "waterway") %>%  # Get all waterways
  osmdata_sf()

# Get COASTLINE data
coastline <- opq(jamaica_bb) %>%
  add_osm_feature(key = "natural", value = "coastline") %>%
  osmdata_sf()

# Extract relevant elements
rivers <- water_features$osm_lines
coast_lines <- coastline$osm_lines

# Get all road networks
roads <- opq(jamaica_bb) %>%
  add_osm_feature(key = "highway") %>%
  osmdata_sf()

# Extract line geometries (roads)
road_lines <- roads$osm_lines
rivers <- water_features$osm_lines
coast_lines <- coastline$osm_lines
```

```{r}
water_polygon <- st_as_sfc(st_bbox(c(xmin = jamaica_bb[1,1], 
                                    xmax = jamaica_bb[1,2],
                                    ymin = jamaica_bb[2,1], 
                                    ymax = jamaica_bb[2,2]),
                           crs = 4326)) %>% 
  st_make_valid()

```

```{r}
coast_lines_clean <- coastline$osm_lines %>% 
  st_make_valid() %>% 
  filter(!st_is_empty(.))
```


```{r}
anyNA(jamaica_bb)
class(water_polygon)
st_crs(water_polygon)$epsg
```


```{r}
base_plot <- ggplot() +
  geom_sf(data = road_lines,
          color = "black",
          size = 0.3,
          alpha = 0.5) +
  
  geom_sf(data = water_polygon,
          fill = "#45B7D1",
          alpha = 0.15) + 
  
  geom_sf(data = coast_lines_clean, 
          color = "#2D3047",
          size = 0.5) +
  theme_void()+
  theme(legend.position = "none")

print(base_plot)

```


```{r road colors}
road_colors <- c(
  "primary" = "#FF6B6B",
  "secondary" = "#4ECDC4",
  "tertiary" = "#45B7D1",
  "residential" = "#96CEB4",
  "unclassified" = "#FFEEAD"
)
```

```{r basic visualization}
art_plot <- ggplot()+
  # First: Coastline base layer
  geom_sf(data = coast_lines_clean,
          color = "#2D3047",
          size = 1.2,
          linetype = "solid") +
  
  
  # Second: Rivers
  geom_sf(data = water_polygon,
          color = "#45B7D1",
          size = 0.4,
          alpha = 0.6) +
  
  # Third: Roads (existing layer)
  geom_sf(data = road_lines,
          aes(color = highway),
          size = 0.2) +

  
  # Rest of your existing styling
  scale_color_manual(values = road_colors) +
  theme_void() +
  theme(legend.position = "none")
print(art_plot)
```

```{r water background}
# Create water background
art_plot <- art_plot +
  
  geom_sf(data = coast_lines_clean,
          color = "#2D3047",
          size = 0.5)

print(art_plot)
```

```{r river pattern waves}
# Add flowing effect to rivers
art_plot <- art_plot +
  geom_sf(data = rivers,
          aes(color = as.numeric(st_length(geometry))),
          size = 0.4,
          alpha = 0.7) +
  scale_color_gradient(low = "#4ECDC4", high = "#2D3047")
```

```{r coastal wave pattern}
# Add wave patterns to coastal areas
wave_pattern <- st_buffer(coast_lines, dist = 0.03) %>%
  st_difference(st_as_sfc(st_bbox(jamaica_bb)))

art_plot <- art_plot +
  geom_sf(data = wave_pattern,
          fill = "white",
          alpha = 0.03,
          color = NA)
```



```{r color by road type}
road_colors <- c(
  "primary" = "#FF6B6B",
  "secondary" = "#4ECDC4",
  "tertiary" = "#45B7D1",
  "residential" = "#96CEB4",
  "unclassified" = "#FFEEAD"
)

art_plot <- ggplot() +
  geom_sf(data = road_lines,
          aes(color = highway),
          size = 0.2,
          alpha = 0.7) +
  scale_color_manual(values = road_colors) +
  theme_void() +
  theme(legend.position = "none")
```


```{r geometric patterns}
set.seed(123)
random_circles <- data.frame(
  x = runif(50, jamaica_bb[1,1], jamaica_bb[1,2]),
  y = runif(50, jamaica_bb[2,1], jamaica_bb[2,2]),
  r = runif(50, 0.01, 0.1)
)

art_plot <- art_plot +
  geom_circle(data = random_circles,
              aes(x0 = x, y0 = y, r = r),
              fill = NA,
              color = "#FF6B6B",
              alpha = 0.3)
print(art_plot)
```

```{r gradient mask}
art_plot <- art_plot +
  geom_regon(aes(x0 = mean(jamaica_bb[1,]), 
                 y0 = mean(jamaica_bb[2,]),
                 sides = 200,
                 r = 1.5,
                 angle = 0),
             fill = radialGradient(c("white", "transparent")),
  alpha = 0.2)
print(art_plot)
```

```{r}
# Generate random noise points
noise_points <- data.frame(
  x = runif(5000, jamaica_bb[1,1], jamaica_bb[1,2]),
  y = runif(5000, jamaica_bb[2,1], jamaica_bb[2,2])
)

art_plot <- art_plot +
  geom_point(data = noise_points,
             aes(x = x, y = y),
             size = 0.1,
             alpha = 0.05,
             color = "white")
print(art_plot)
```

```{r}
# Polar coordinate transformation
art_plot <- art_plot +
  coord_polar() +
  scale_x_continuous(limits = c(-78.5, -76)) +
  scale_y_continuous(limits = c(17.7, 18.5))
print(art_plot)
```

